## IMPORT

In [39]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.cluster import KMeans
import numpy as np
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [40]:
df = pd.read_csv("../../Supervise.csv")
matrices = np.load('../../Matrice.npy', allow_pickle=True)

X = matrices
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    stratify=y,
    random_state=1
)

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=1)

clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)

accuracy = clf.score(X_test, y_test)

print("Accuracy :", accuracy)


y_pred = clf.predict(X_test)

print(confusion_matrix(y_test, y_pred))


Accuracy : 0.7326478149100257
[[883   0  44   0]
 [  0 800 470   0]
 [  0   0 344   0]
 [  0   0 318 253]]
