## IMPORTS

In [2]:
from sklearn import svm
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.cluster import KMeans
import numpy as np
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
try:
    df = pd.read_csv("../../Supervise.csv") # Ouvre le csv
except FileNotFoundError:
    raise SystemExit(84)

matrices = np.load('../../Matrice.npy', allow_pickle=True) # Ouvre les matrices

X = matrices # Donne les matrices en données afin qu'il classe les IRM des patients en fonction de leurs maladie
y = df["target"] # Donne les différentes maladies possibles

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    stratify=y,
    random_state=1
) # Split X et Y pour avoir une partie entraînement et une partie examen

clf = svm.SVC().fit(X_train, y_train) # Créer et entraîne le modèle

accuracy = clf.score(X_test, y_test) # Calcule la précision du bot ( le % d'IRM qu'il arrive a classer )

print("Accuracy :", accuracy) # Print la précision


y_pred = clf.predict(X_test)

print(confusion_matrix(y_test, y_pred)) # Créer la matrice de précision pour savoir avec plus de précision comment le bot arrive à classer les différentes maladies genre à combien de pourcent il devine que les patients atteint de stone sont atteint de stone.

raise SystemExit(0)


Accuracy : 1.0
[[ 927    0    0    0]
 [   0 1270    0    0]
 [   0    0  344    0]
 [   0    0    0  571]]


In [3]:
try:
    df = pd.read_csv("../../Supervise.csv") # Ouvre le csv
except FileNotFoundError:
    raise SystemExit(84)

matrices = np.load('../../Matrice.npy', allow_pickle=True) # Ouvre les matrices

X = matrices # Donne les matrices en données afin qu'il classe les IRM des patients en fonction de leurs maladie
y = df["target"] # Donne les différentes maladies possibles
groupes = df['groupe']

gss = GroupShuffleSplit(n_splits=5, test_size=0.2, random_state=1)
train_idx, test_idx = next(gss.split(X, y, groups=groupes))

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)   # fit SEULEMENT sur train
X_test = scaler.transform(X_test)
    
clf = svm.SVC().fit(X_train, y_train) # Créer et entraîne le modèle

accuracy = clf.score(X_test, y_test) # Calcule la précision du bot (le % d'IRM qu'il arrive a classer)

print("Accuracy :", accuracy) # Print la précision


y_pred = clf.predict(X_test)

print(confusion_matrix(y_test, y_pred)) 

raise SystemExit(0)

Accuracy : 0.5722911774572291
[[579   0 100  15]
 [ 37 872 455 270]
 [ 30  13  74  18]
 [ 74 164  99 181]]


SystemExit: 0

/home/gabin/Documents/Project/B-SPE-311-LIL-3-1-cvrie-2/Myvenv/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3831: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


Resultat avec un similarity de 0.9
```
Accuracy : 0.5722911774572291
[[579   0 100  15]
 [ 37 872 455 270]
 [ 30  13  74  18]
 [ 74 164  99 181]]
```

